[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.install]
cmds = ["dotnet restore backend/DesignPlanner.Api/DesignPlanner.Api.csproj"]

[phases.build]
cmds = ["dotnet publish backend/DesignPlanner.Api/DesignPlanner.Api.csproj --no-restore -c Release -o out"]

[start]
cmd = "./out/DesignPlanner.Api --urls=http://0.0.0.0:$PORT"
