[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.install]
cmds = ["cd backend/DesignPlanner.Api && dotnet restore"]

[phases.build]
cmds = ["cd backend/DesignPlanner.Api && dotnet publish --no-restore -c Release -o out"]

[start]
cmd = "cd backend/DesignPlanner.Api && dotnet run --urls=http://0.0.0.0:$PORT"
